# Generated by Django 4.2.1 on 2023-06-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('clas', models.PositiveBigIntegerField()),
                ('age', models.PositiveBigIntegerField()),
                ('school', models.PositiveBigIntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeModel',
        ),
    ]
