# Generated by Django 4.2.1 on 2023-06-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registermodel_delete_homemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='RegisterModell',
        ),
    ]
